# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=7)),
                ('size', models.IntegerField(choices=[(1, 'Large'), (2, 'Medium'), (3, 'Small')], default=1)),
                ('flip', models.CharField(choices=[('horizon', 'Flip Horizontally'), ('vertical', 'Flip Vertically'), ('NONE', 'None')], default='NONE', max_length=17)),
                ('rotate', models.CharField(choices=[('clock', 'Clockwise'), ('anti', 'Anticlockwise'), ('NONE', 'None')], default='NONE', max_length=15)),
                ('blur', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=5)),
                ('document', models.ImageField(upload_to=portal.models.get_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=100)),
                ('Last_Name', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=30)),
                ('DOB', models.DateTimeField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to=portal.models.get_profile_name)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
