# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170912_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1),
        ),
    ]
