# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170924_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='effect',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Aqua'), (3, 'Seaform'), (4, 'Grayscale'), (5, 'Retro'), (6, 'Edges')], default=1),
        ),
    ]
