# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170912_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(choices=[(1, 'Large'), (2, 'Medium'), (3, 'Small')], default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=7),
        ),
    ]
