# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171003_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rotate',
            field=models.CharField(choices=[('clock', 'Clockwise'), ('anti', 'Anticlockwise'), ('NONE', 'None')], default='NONE', max_length=15),
        ),
    ]
