# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_document_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='effect',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Aqua'), (3, 'Seaform'), (4, 'Grayscale'), (5, 'Retro'), (6, 'Edges'), (7, 'Negative'), (8, 'Sepia')], default=1),
        ),
    ]
