# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20170919_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
