# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20171003_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='height',
            field=models.IntegerField(blank=True, default=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='width',
            field=models.IntegerField(blank=True, default=500),
        ),
    ]
