# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20171003_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default_profile.jpg', upload_to=portal.models.get_profile_name),
        ),
    ]
