# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_document_flip'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rotate',
            field=models.CharField(choices=[('clock', 'Clockwise'), ('anti', 'Anticlockwise'), ('NONE', 'None')], default='NONE', max_length=15),
        ),
    ]
