# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0008_auto_20171027_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='like_or_not',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='hello', to=settings.AUTH_USER_MODEL),
        ),
    ]
