# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_document_rotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='blur',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=5),
        ),
    ]
