# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=225),
        ),
    ]
