# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
