# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_comments_uploaded_at'),
        ('portal', '0010_comments_uploaded_at'),
    ]

    operations = [
    ]
