# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_delete_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reset',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
    ]
