# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_document_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='reset',
        ),
        migrations.AddField(
            model_name='document',
            name='effect',
            field=models.IntegerField(choices=[(1, 'Filter 1'), (2, 'Filter 2'), (3, 'Filter 3')], default=1),
        ),
    ]
