# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_merge_20171109_2010'),
        ('portal', '0012_merge_20171111_1047'),
    ]

    operations = [
    ]
