# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20170926_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reset',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='effect',
            field=models.IntegerField(choices=[(1, 'Original'), (2, 'Filter 2'), (3, 'Filter 3'), (4, 'Filter 4'), (5, 'Filter 5'), (6, 'Filter 6')], default=1),
        ),
    ]
