# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_merge_20171112_1835'),
        ('portal', '0009_auto_20171112_1126'),
    ]

    operations = [
    ]
