# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20171202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_profile.jpg', null=True, upload_to=portal.models.get_profile_name),
        ),
    ]
