# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20171202_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='uploaded_at',
        ),
    ]
