# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170920_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='flip',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
