# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(unique=True, upload_to='documents/'),
        ),
    ]
