# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20170919_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to=portal.models.get_file_name),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
