# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review')], default=1),
        ),
    ]
