# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_document_flip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='flip',
        ),
    ]
